name: Draft Release Notes

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Create or update Release Draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
